// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoYVsFcQFfn0hbg27sK7hFQcYz-yTcPlI',
    appId: '1:510814530616:web:3b45ca4cda83bbcce98acd',
    messagingSenderId: '510814530616',
    projectId: 'my-smart-mirror-1234',
    authDomain: 'my-smart-mirror-1234.firebaseapp.com',
    storageBucket: 'my-smart-mirror-1234.firebasestorage.app',
    measurementId: 'G-7DL742WTSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7V6p2KIG1QiSRpblrJvkQ1sWIT-ppk70',
    appId: '1:510814530616:android:a451f559c846c66ce98acd',
    messagingSenderId: '510814530616',
    projectId: 'my-smart-mirror-1234',
    storageBucket: 'my-smart-mirror-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0N8IYrX1T32ijhGkBlMSd0FWYntfFuNQ',
    appId: '1:510814530616:ios:3618c27df731fc14e98acd',
    messagingSenderId: '510814530616',
    projectId: 'my-smart-mirror-1234',
    storageBucket: 'my-smart-mirror-1234.firebasestorage.app',
    iosBundleId: 'com.example.mySmartMirrorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0N8IYrX1T32ijhGkBlMSd0FWYntfFuNQ',
    appId: '1:510814530616:ios:3618c27df731fc14e98acd',
    messagingSenderId: '510814530616',
    projectId: 'my-smart-mirror-1234',
    storageBucket: 'my-smart-mirror-1234.firebasestorage.app',
    iosBundleId: 'com.example.mySmartMirrorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoYVsFcQFfn0hbg27sK7hFQcYz-yTcPlI',
    appId: '1:510814530616:web:bc1376ce3c3c6a4fe98acd',
    messagingSenderId: '510814530616',
    projectId: 'my-smart-mirror-1234',
    authDomain: 'my-smart-mirror-1234.firebaseapp.com',
    storageBucket: 'my-smart-mirror-1234.firebasestorage.app',
    measurementId: 'G-MYD2GSYYF7',
  );
}
